version: '3'
networks:
  cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      cluster-net:
        ipv4_address: 172.29.0.51